### ISSUE TITLE
fix sendgrid.SendGridAPIClient interface change

### ISSUE THREAD

**Issue by bbelderbos** [PyBites-Open-Source/pbreadinglist#26]
`sg = sendgrid.SendGridAPIClient(apikey=config('SENDGRID_API_KEY'))` => `TypeError: __init__() got an unexpected keyword argument 'apikey'` probably caused by https://github.com/PyBites-Open-Source/pbreadinglist/commit/dd8d78bfe2844365ea5f677991f1c6ee6951d997

**Comment by pybites** [comment]
fixed https://github.com/PyBites-Open-Source/pbreadinglist/pull/30
